name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync
    
    - name: Lint with ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .
    
    - name: Test imports
      run: |
        uv run python -c "import main; print('✅ Main module imports successfully')"
    
    - name: Test basic functionality (without credentials)
      run: |
        uv run python -c "
        import main
        from fastapi.testclient import TestClient
        
        # Test without credentials (should work in development mode)
        client = TestClient(main.app)
        
        # Test health check
        response = client.get('/')
        assert response.status_code == 200
        print('✅ Health check passed')
        
        # Test models endpoint (should work without auth when no API_KEY/HF_TOKEN set)
        response = client.get('/v1/models')
        assert response.status_code == 200
        print('✅ Models endpoint passed')
        
        print('✅ All basic tests passed')
        "
